nominalCapacity: float
minVoltage: float
maxVoltage: float
nominalVoltage: float
eodVoltage: float
eocVoltage: float
contChargeCurrent: float
peakChargeCurrent: float
contDischargeCurrent: float
peakDischargeCurrent: float
minChargeTemperature: float
maxChargeTemperature: float
minDischargeTemperature: float
maxDischargeTemperature: float
weight: float
nominalCurrent: float
energyDensity: float
internalResistance: float
