stages:
  - build

pages:
  stage: build
  image: node:14.19.3-slim
  artifacts:
    paths:
      - public
  cache:
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - ./make.sh
