from typing import List

from bmgen.base_generator import BaseGenerator
from bmgen.targets.jsonld.ast import Program, Step, create_property, Reference
from bmgen.targets.jsonld import battery
import cold.models.autogenerated as cold


class JSONLDGenerator(BaseGenerator):
    def __init__(self):
        super().__init__()
        self.program = Program([])

    def finish(self):
        pass

    def add(self, step):
        self.program.steps.append(step)
        return step

    def ast(self):
        self.finish()
        return str(self.program)

    def generate_battery(self):
        return cold.Battery(
            hasProperty=[
                create_property(cold.NominalCapacity, Reference("battery_nominal_capacity")),
                create_property(cold.UpperVoltageLimit, Reference("battery_eoc_voltage")),
                create_property(cold.LowerVoltageLimit, Reference("battery_eod_voltage")),
                create_property(cold.MaximumContinuousChargingCurrent, Reference("battery_cont_charge_current")),
                create_property(cold.MaximumContinuousDischargingCurrent, Reference("battery_cont_discharge_current")),
                create_property(cold.InternalResistance, Reference("battery_internal_resistance")),
                create_property(cold.EnergyDensity, Reference("battery_energy_density")),
            ]
        )

    def generate(self):
        self.finish()
        program = self.program.toCold()
        program.hasParticipant = self.generate_battery()
        return program