version: "3"
services:
  frontend:
    ports:
      - "24642:80"
    image: git.isea.rwth-aachen.de:5050/ess/testing/bmgen:frontend

  backend:
    image: git.isea.rwth-aachen.de:5050/ess/testing/bmgen:backend
