try:
    import cold.models.autogenerated
    from cold.models.autogenerated import CellVoltage
except:
    import cold.scripts.regenerate_models
    import os

    oldpath = os.getcwd()
    os.chdir(os.path.join(os.path.dirname(cold.__file__), '..'))
    cold.scripts.regenerate_models.main()
    os.chdir(oldpath)


from bmgen.battery import Battery
from bmgen.targets.jsonld.generators.jsonld_generator import JSONLDGenerator
from bmgen.transformer import Transformer

generator: JSONLDGenerator
battery: Battery

default_format = "json"
