import cold.models.autogenerated as cold

from bmgen.battery import CyclerBattery
from bmgen.targets.jsonld.ast import Parameter

battery = CyclerBattery(
    # nominalCapacity=Parameter(cold.NominalCapacity),
    maxVoltage=Parameter(cold.UpperVoltageLimit, cold.Volt()),
    minVoltage=Parameter(cold.LowerVoltageLimit, cold.Volt()),
    eocVoltage=Parameter(cold.UpperVoltageLimit, cold.Volt()),
    eodVoltage=Parameter(cold.LowerVoltageLimit, cold.Volt()),
    contChargeCurrent=Parameter(cold.MaximumContinuousChargingCurrent, cold.Ampere()),
    contDischargeCurrent=Parameter(
        cold.MaximumContinuousDischargingCurrent, cold.Ampere()
    ),
    # internalResistance=Parameter(cold.InternalResistance),
    # energyDensity=Parameter(cold.EnergyDensity, cold.()),
    oneC=Parameter(cold.AmperePerAmpereHour, cold.AmperePerAmpereHour()),
)
