import cold.models.autogenerated as cold

import bmgen.targets.jsonld.ast as ast

I = ast.Channel(cold.CellCurrent, cold.Ampere)
V = ast.Channel(cold.CellVoltage, cold.Volt)
t = ast.Channel(cold.StepTime, cold.Second)
# StepCharge = ast.BCLTerminationType("charge")
