import cold.models.autogenerated as cold

import bmgen.targets.jsonld.ast as ast

I = ast.Parameter(cold.CellCurrent, cold.Ampere())
V = ast.Parameter(cold.CellVoltage, cold.Volt())
t = ast.Parameter(cold.StepTime, cold.Second())
# StepCharge = ast.BCLTerminationType("charge")
