import cold.models.autogenerated as cold

LOWER_LIMITS = {
    cold.CellCurrent: cold.TerminationQuantity,
    cold.CellVoltage: cold.LowerVoltageLimit,
}

UPPER_LIMITS = {
    cold.CellCurrent: cold.TerminationQuantity,
    cold.CellVoltage: cold.UpperVoltageLimit,
}

TERMINATION_UNITS = {
    "ElectricCurrent": "Ampere",
    "Voltage": "Volt",
    "time": "Second",
    "charge": "AmpereHour",
}
