from dataclasses import dataclass
from typing import Any, List

import cold.models.autogenerated as cold

import bmgen.targets.jsonld as target
import bmgen.targets.jsonld.ast as ast
import bmgen.targets.jsonld.channel as channel
from bmgen.targets.jsonld.helper.cast import autocast, limitcast


@autocast(current=cold.Ampere, voltage=cold.Volt)
def charge(
    current: float,
    voltage: float | None = None,
    limits: List[ast.Limit] | None = None,
    registrations: Any = None,
):
    if voltage is None:
        chargeStep = target.generator.add(
            ast.Step(
                cold.ConstantCurrentCharging(),
                [ast.Setpoint(cold.ChargingCurrent, current)],
                limits or [],
            )
        )
    else:
        chargeStep = target.generator.add(
            ast.Step(
                cold.ConstantCurrentConstantVoltageCharging(),
                [
                    ast.Setpoint(cold.ChargingCurrent, current),
                    ast.Setpoint(cold.ChargingVoltage, voltage),
                ],
                limits or [],
            )
        )
    return chargeStep


@autocast(current=cold.Ampere, voltage=cold.Volt)
def discharge(
    current: float,
    voltage: float | None = None,
    limits: List[ast.Limit] | None = None,
    registrations: Any = None,
):
    if voltage is None:
        dischargeStep = target.generator.add(
            ast.Step(
                cold.ConstantCurrentDischarging(),
                [ast.Setpoint(cold.DischargingCurrent, current)],
                limits or [],
            )
        )
    else:
        dischargeStep = target.generator.add(
            ast.Step(
                cold.ConstantCurrentConstantVoltageDischarging(),
                [
                    ast.Setpoint(cold.DischargingCurrent, current),
                    ast.Setpoint(cold.DischargingVoltage, voltage),
                ],
                limits or [],
            )
        )
    return dischargeStep


def pause(
    limits: List[ast.Limit] | None = None,
    hours: float | None = None,
    minutes: float | None = None,
    seconds: float | None = None,
    registrations: Any = None,
):
    return target.generator.add(
        ast.Step(
            cold.ConstantCurrentCharging(),
            [
                ast.Setpoint(
                    cold.ChargingCurrent, ast.NumericLiteral(0, cold.Ampere())
                ),
                time(hours, minutes, seconds).toValue(),
            ],
            limits or [],
        )
    )


@dataclass
class time:
    hours: float | None = None
    minutes: float | None = None
    seconds: float | None = None

    def toValue(self) -> ast.Setpoint:
        value = 0.0
        if self.seconds is not None:
            value = self.seconds
        if self.minutes is not None:
            value += self.minutes * 60
        if self.hours is not None:
            value += self.hours * 3600
        return ast.Setpoint(cold.StepDuration, ast.NumericLiteral(value, cold.Second()))

    def toCold(self):
        return self.toValue().toCold()

    # def toLimit(self) -> ast.BCLTermination:
    #     return ast.BCLTermination(channel.t, value=self.toValue())


def seconds(value: float) -> time:
    return time(None, None, value)


def minutes(value: float) -> time:
    return time(None, value, None)


def hours(value: float) -> time:
    return time(value, None, None)


def limit(condition: ast.BCLTermination, action: Any | None = None):
    # if action is not None:
    #     raise Exception("Limit actions not supported for BCL")
    return condition


def limit_global(condition: ast.BCLTermination, action: Any | None = None):
    # raise Exception("Global limits not supported for BCL")
    return None


def error(errnum: int):
    # raise Exception("Errors not supported for BCL")
    return None


def register_global(
    time: time | None = None,
    voltage: ast.BCLValue | None = None,
    current: ast.BCLValue | None = None,
    format: List | None = None,
):
    pass


def register(
    time: time | None = None,
    voltage: ast.BCLValue | None = None,
    current: ast.BCLValue | None = None,
    format: List | None = None,
):
    pass
